version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - custom_network

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile_app
    ports:
      - "4000:4000"
    volumes:
      - .:/app
#    environment:
#      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydatabase
#    depends_on:
#      - postgres
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge


volumes:
  postgres_data:
